import Head from "next/head";
import { useRouter } from "next/router";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useTranslation } from "@/hooks/useTranslation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const { translate } = useTranslation();

  const [username, password, description] = translate([
    "username",
    "password",
    "description",
  ]);

  const changeLanguageAction = (lang: string) => {
    const { pathname, asPath, query } = router;
    router.push({ pathname, query }, asPath, { locale: lang });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <select
          onChange={(e) => {
            const { value } = e.target;
            changeLanguageAction(value);
          }}
          defaultValue={router.locale}
        >
          <option value="en">English</option>
          <option value="sp">Spanish</option>
        </select>

        <div className="">
          <label htmlFor={username}>{username}</label>
          <input type="text" id={username} placeholder={username} />
        </div>
        <div className="">
          <label htmlFor={password}>{password}</label>
          <input type="text" id={password} placeholder={password} />
        </div>

        <p>{description}</p>
      </main>
    </>
  );
}
